#! /bin/bash

# Autogenerated File: DO NOT EDIT
# Systemctl related hacks BEGIN
function start {
    sudo systemctl start $1
}
function stop {
    sudo systemctl stop $1
}
function reload {
    sudo systemctl reload $1
}
function enable {
    sudo systemctl enable $1
}
function disable {
    sudo systemctl disable $1
}
function status {
    sudo systemctl status $1
}
function restart {
    sudo systemctl restart $1
}
# Systemctl related hacks END
